# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OUyrHNCx0allvER7NmSB-CM7XeRPJ4tX
"""

def greet():
    print("      WELCOME TO PYTHON BANK")
greet()
balance = 0
while True:
    print("\n1. Deposit")
    print("2. Withdraw")
    print("3. Check Balance")
    print("4. Exit")
    choice = int(input("Enter your choice: "))
    if choice == 1:
        amount = float(input("Enter amount to deposit: ₹"))
        balance += amount
        print("Amount Deposited Successfully")
    elif choice == 2:
        amount = float(input("Enter amount to withdraw: ₹"))
        if amount <= balance:
            balance -= amount
            print("Amount Withdrawn Successfully")
        else:
            print("Insufficient Balance")
    elif choice == 3:
        print("Current Balance: ₹", balance)
    elif choice == 4:
        print("Thank You for Banking with Us")
        break
    else:
        print("Invalid Choice")

def greet():
    print("      WELCOME TO PYTHON BANK")
greet()
balance = 0
account_created = False
while True:
    print("\n1. Create Account")
    print("2. Check Balance")
    print("3. Deposit Money")
    print("4. Withdraw Money")
    print("5. Exit")
    choice = int(input("Enter your choice: "))
    if choice == 1:
        if account_created:
            print("Account already exists.")
        else:
            name = input("Enter Account Holder Name: ")
            account_number = input("Enter Account Number: ")
            account_created = True
            print("Account Created Successfully!")
    elif choice == 2:
        if account_created:
            print("Current Balance: ₹", balance)
        else:
            print("Please create an account first.")
    elif choice == 3:
        if account_created:
            amount = float(input("Enter amount to deposit: ₹"))
            balance += amount
            print("Amount Deposited Successfully.")
        else:
           print("Please create an account first.")
    elif choice == 4:
        if account_created:
            amount = float(input("Enter amount to withdraw: ₹"))

            if amount <= balance:
                balance -= amount
                print("Amount Withdrawn Successfully.")
            else:
                print("Insufficient Balance.")
        else:
            print("Please create an account first.")
    elif choice == 5:
        print("Thank You for Banking with Us!")
        break
    else:
        print("Invalid Choice.")

def greet():
    print("      WELCOME TO PYTHON BANK")
greet()
try:
    f = open("account.txt", "r")
    data = f.readlines()
    f.close()

    name = data[0].strip()
    account_number = data[1].strip()
    balance = float(data[2].strip())
    account_created = True

except:
    account_created = False
    balance = 0

while True:
    print("\n1. Create Account")
    print("2. Check Balance")
    print("3. Deposit Money")
    print("4. Withdraw Money")
    print("5. Exit")

    choice = int(input("Enter your choice: "))

    if choice == 1:
        if account_created:
            print("Account already exists.")
        else:
            name = input("Enter Account Holder Name: ")
            account_number = input("Enter Account Number: ")
            balance = 0

            f = open("account.txt", "w")
            f.write(name + "\n")
            f.write(account_number + "\n")
            f.write(str(balance))
            f.close()

            account_created = True
            print("Account Created Successfully!")

    elif choice == 2:
        if account_created:
            print("\nAccount Holder :", name)
            print("Account Number :", account_number)
            print("Current Balance: ₹", balance)
        else:
            print("Please create an account first.")

    elif choice == 3:
        if account_created:
            amount = float(input("Enter amount to deposit: ₹"))
            balance += amount

            f = open("account.txt", "w")
            f.write(name + "\n")
            f.write(account_number + "\n")
            f.write(str(balance))
            f.close()

            print("Amount Deposited Successfully.")
        else:
            print("Please create an account first.")

    elif choice == 4:
        if account_created:
            amount = float(input("Enter amount to withdraw: ₹"))

            if amount <= balance:
                balance -= amount

                f = open("account.txt", "w")
                f.write(name + "\n")
                f.write(account_number + "\n")
                f.write(str(balance))
                f.close()

                print("Amount Withdrawn Successfully.")
            else:
                print("Insufficient Balance.")
        else:
            print("Please create an account first.")

    elif choice == 5:
        print("Thank You for Banking with Us!")
        break

    else:
        print("Invalid Choice.")